"""add_users_table_and_map_user_relation

Revision ID: 5c4ad958ac85
Revises: a1b2c3d4e5f6
Create Date: 2025-12-18 21:46:22.475775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4ad958ac85'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.add_column('maps', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_maps_user_id'), 'maps', ['user_id'], unique=False)
    op.create_foreign_key(None, 'maps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_pois_is_referenced'), table_name='pois')
    op.create_index(op.f('ix_pois_is_referenced'), 'pois', ['is_referenced'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pois_is_referenced'), table_name='pois')
    op.create_index(op.f('idx_pois_is_referenced'), 'pois', ['is_referenced'], unique=False)
    op.drop_constraint(None, 'maps', type_='foreignkey')
    op.drop_index(op.f('ix_maps_user_id'), table_name='maps')
    op.drop_column('maps', 'user_id')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
