"""add_async_operations_table

Revision ID: 2283f3539ae2
Revises: 2c07a6a50c72
Create Date: 2025-12-14 13:56:39.379096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2283f3539ae2'
down_revision: Union[str, None] = '2c07a6a50c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_call_operation_created', 'api_call_logs', ['operation', 'created_at'], unique=False)
    op.create_index('idx_api_call_provider_created', 'api_call_logs', ['provider', 'created_at'], unique=False)
    op.create_index('idx_api_call_provider_operation', 'api_call_logs', ['provider', 'operation'], unique=False)
    op.create_index(op.f('ix_api_call_logs_created_at'), 'api_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_call_logs_operation'), 'api_call_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_api_call_logs_provider'), 'api_call_logs', ['provider'], unique=False)
    op.create_table('async_operations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_async_op_status_started', 'async_operations', ['status', 'started_at'], unique=False)
    op.create_index('idx_async_op_type_status', 'async_operations', ['operation_type', 'status'], unique=False)
    op.create_index(op.f('ix_async_operations_operation_type'), 'async_operations', ['operation_type'], unique=False)
    op.create_index(op.f('ix_async_operations_started_at'), 'async_operations', ['started_at'], unique=False)
    op.create_index(op.f('ix_async_operations_status'), 'async_operations', ['status'], unique=False)
    op.drop_table('cache_stats')
    op.alter_column('cache_entries', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('cache_entries', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('cache_entries', 'operation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_cache_expires_at'), table_name='cache_entries')
    op.drop_index(op.f('idx_cache_operation'), table_name='cache_entries')
    op.drop_index(op.f('idx_cache_params'), table_name='cache_entries', postgresql_using='gin')
    op.drop_index(op.f('idx_cache_provider'), table_name='cache_entries')
    op.create_index('idx_cache_provider_operation', 'cache_entries', ['provider', 'operation'], unique=False)
    op.create_index(op.f('ix_cache_entries_expires_at'), 'cache_entries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cache_entries_operation'), 'cache_entries', ['operation'], unique=False)
    op.create_index(op.f('ix_cache_entries_provider'), 'cache_entries', ['provider'], unique=False)
    op.alter_column('google_places_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_google_places_cache_google_place_id'), 'google_places_cache', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_pois_primary_provider'), 'pois', ['primary_provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pois_primary_provider'), table_name='pois')
    op.drop_index(op.f('ix_google_places_cache_google_place_id'), table_name='google_places_cache')
    op.alter_column('google_places_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cache_entries_provider'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_operation'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_expires_at'), table_name='cache_entries')
    op.drop_index('idx_cache_provider_operation', table_name='cache_entries')
    op.create_index(op.f('idx_cache_provider'), 'cache_entries', ['provider'], unique=False)
    op.create_index(op.f('idx_cache_params'), 'cache_entries', ['params'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_cache_operation'), 'cache_entries', ['operation'], unique=False)
    op.create_index(op.f('idx_cache_expires_at'), 'cache_entries', ['expires_at'], unique=False)
    op.alter_column('cache_entries', 'operation',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cache_entries', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cache_entries', 'key',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('cache_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('total_entries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('misses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evictions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hit_rate_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cache_stats_pkey'))
    )
    op.drop_index(op.f('ix_async_operations_status'), table_name='async_operations')
    op.drop_index(op.f('ix_async_operations_started_at'), table_name='async_operations')
    op.drop_index(op.f('ix_async_operations_operation_type'), table_name='async_operations')
    op.drop_index('idx_async_op_type_status', table_name='async_operations')
    op.drop_index('idx_async_op_status_started', table_name='async_operations')
    op.drop_table('async_operations')
    op.drop_index(op.f('ix_api_call_logs_provider'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_operation'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_created_at'), table_name='api_call_logs')
    op.drop_index('idx_api_call_provider_operation', table_name='api_call_logs')
    op.drop_index('idx_api_call_provider_created', table_name='api_call_logs')
    op.drop_index('idx_api_call_operation_created', table_name='api_call_logs')
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
