"""add_here_maps_support_to_pois

Revision ID: 2c07a6a50c72
Revises: 75055590603b
Create Date: 2025-12-14 10:20:30.383376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c07a6a50c72'
down_revision: Union[str, None] = '75055590603b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Skip cache_entries alterations - they work fine as TEXT
    # op.alter_column('cache_entries', 'key', ...)
    # op.alter_column('cache_entries', 'provider', ...)
    # op.alter_column('cache_entries', 'operation', ...)

    # Skip index changes for cache_entries - existing indexes are fine
    # op.drop_index(op.f('idx_cache_expires_at'), table_name='cache_entries')
    # ...

    # Skip google_places_cache alterations
    # op.alter_column('google_places_cache', 'created_at', ...)

    # Add HERE Maps support columns to pois table
    # First add columns as nullable
    op.add_column('pois', sa.Column('primary_provider', sa.String(length=20), nullable=True))
    op.add_column('pois', sa.Column('here_id', sa.String(length=100), nullable=True))
    op.add_column('pois', sa.Column('here_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pois', sa.Column('enriched_by', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pois', sa.Column('last_enriched_at', sa.DateTime(), nullable=True))

    # Set default values for existing records
    op.execute("UPDATE pois SET primary_provider = 'osm' WHERE primary_provider IS NULL")
    op.execute("UPDATE pois SET enriched_by = '[]'::jsonb WHERE enriched_by IS NULL")

    # Now make columns NOT NULL where needed
    op.alter_column('pois', 'primary_provider', nullable=False, server_default='osm')
    op.alter_column('pois', 'enriched_by', nullable=False, server_default='[]')

    # Create indexes
    op.create_index('idx_pois_provider', 'pois', ['primary_provider'], unique=False)
    op.create_index(op.f('ix_pois_here_id'), 'pois', ['here_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_pois_here_id'), table_name='pois')
    op.drop_index('idx_pois_provider', table_name='pois')

    # Drop columns
    op.drop_column('pois', 'last_enriched_at')
    op.drop_column('pois', 'enriched_by')
    op.drop_column('pois', 'here_data')
    op.drop_column('pois', 'here_id')
    op.drop_column('pois', 'primary_provider')
    # ### end Alembic commands ###
