"""initial_schema

Revision ID: 57b038ef1196
Revises: 
Create Date: 2025-11-30 21:57:37.131420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57b038ef1196'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new tables for maps and POIs
    op.create_table('maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=500), nullable=False),
    sa.Column('destination', sa.String(length=500), nullable=False),
    sa.Column('total_length_km', sa.Float(), nullable=False),
    sa.Column('road_id', sa.String(length=200), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pois',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('osm_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('operator', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('opening_hours', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('cuisine', sa.String(length=200), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pois_location', 'pois', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_pois_type_city', 'pois', ['type', 'city'], unique=False)
    op.create_index(op.f('ix_pois_brand'), 'pois', ['brand'], unique=False)
    op.create_index(op.f('ix_pois_city'), 'pois', ['city'], unique=False)
    op.create_index(op.f('ix_pois_name'), 'pois', ['name'], unique=False)
    op.create_index(op.f('ix_pois_osm_id'), 'pois', ['osm_id'], unique=True)
    op.create_index(op.f('ix_pois_type'), 'pois', ['type'], unique=False)
    op.create_table('map_pois',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=True),
    sa.Column('distance_from_origin_km', sa.Float(), nullable=False),
    sa.Column('distance_from_road_meters', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('junction_distance_km', sa.Float(), nullable=True),
    sa.Column('junction_lat', sa.Float(), nullable=True),
    sa.Column('junction_lon', sa.Float(), nullable=True),
    sa.Column('requires_detour', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_map_pois_map_distance', 'map_pois', ['map_id', 'distance_from_origin_km'], unique=False)
    op.create_index('idx_map_pois_map_poi', 'map_pois', ['map_id', 'poi_id'], unique=True)
    op.create_index(op.f('ix_map_pois_map_id'), 'map_pois', ['map_id'], unique=False)
    op.create_index(op.f('ix_map_pois_poi_id'), 'map_pois', ['poi_id'], unique=False)

    # Create cache_entries table
    op.create_table('cache_entries',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_cache_expires_at', 'cache_entries', ['expires_at'], unique=False)
    op.create_index('idx_cache_operation', 'cache_entries', ['operation'], unique=False)
    op.create_index('idx_cache_provider', 'cache_entries', ['provider'], unique=False)
    op.create_index('idx_cache_params', 'cache_entries', ['params'], unique=False, postgresql_using='gin')
    op.create_index('idx_cache_operation_expires', 'cache_entries', ['operation', 'expires_at'], unique=False)

    # Create google_places_cache table
    op.create_table('google_places_cache',
    sa.Column('osm_poi_id', sa.String(length=100), nullable=False),
    sa.Column('google_place_id', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('user_rating_count', sa.Integer(), nullable=True),
    sa.Column('google_maps_uri', sa.Text(), nullable=True),
    sa.Column('matched_name', sa.String(length=500), nullable=True),
    sa.Column('match_distance_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('search_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('search_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('search_name', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('osm_poi_id'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1.0 AND rating <= 5.0)', name='valid_rating'),
    sa.CheckConstraint('user_rating_count IS NULL OR user_rating_count >= 0', name='valid_review_count')
    )
    op.create_index('idx_google_places_expires', 'google_places_cache', ['expires_at'], unique=False)
    op.create_index('idx_google_places_google_id', 'google_places_cache', ['google_place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop google_places_cache
    op.drop_index('idx_google_places_google_id', table_name='google_places_cache')
    op.drop_index('idx_google_places_expires', table_name='google_places_cache')
    op.drop_table('google_places_cache')

    # Drop cache_entries
    op.drop_index('idx_cache_operation_expires', table_name='cache_entries')
    op.drop_index('idx_cache_params', table_name='cache_entries', postgresql_using='gin')
    op.drop_index('idx_cache_provider', table_name='cache_entries')
    op.drop_index('idx_cache_operation', table_name='cache_entries')
    op.drop_index('idx_cache_expires_at', table_name='cache_entries')
    op.drop_table('cache_entries')

    # Drop the new tables only
    op.drop_index(op.f('ix_map_pois_poi_id'), table_name='map_pois')
    op.drop_index(op.f('ix_map_pois_map_id'), table_name='map_pois')
    op.drop_index('idx_map_pois_map_poi', table_name='map_pois')
    op.drop_index('idx_map_pois_map_distance', table_name='map_pois')
    op.drop_table('map_pois')
    op.drop_index(op.f('ix_pois_type'), table_name='pois')
    op.drop_index(op.f('ix_pois_osm_id'), table_name='pois')
    op.drop_index(op.f('ix_pois_name'), table_name='pois')
    op.drop_index(op.f('ix_pois_city'), table_name='pois')
    op.drop_index(op.f('ix_pois_brand'), table_name='pois')
    op.drop_index('idx_pois_type_city', table_name='pois')
    op.drop_index('idx_pois_location', table_name='pois')
    op.drop_table('pois')
    op.drop_table('maps')
    # ### end Alembic commands ###
