"""add is_admin and last_login_at to users

Revision ID: 6d5287c4f909
Revises: 5c4ad958ac85
Create Date: 2025-12-21 17:34:45.027199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5287c4f909'
down_revision: Union[str, None] = '5c4ad958ac85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # Set Renato Mintz as admin by default
    op.execute("UPDATE users SET is_admin = true WHERE name = 'Renato Mintz'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
