"""add_user_events_table

Revision ID: 0a47b69ae583
Revises: 1d897032655c
Create Date: 2026-01-04 10:01:37.112051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a47b69ae583'
down_revision: Union[str, None] = '1d897032655c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('page_path', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_event_category_created', 'user_events', ['event_category', 'created_at'], unique=False)
    op.create_index('idx_user_event_category_type', 'user_events', ['event_category', 'event_type'], unique=False)
    op.create_index('idx_user_event_device_created', 'user_events', ['device_type', 'created_at'], unique=False)
    op.create_index('idx_user_event_session_created', 'user_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_user_event_type_created', 'user_events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_user_event_user_created', 'user_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_events_created_at'), 'user_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_events_event_category'), 'user_events', ['event_category'], unique=False)
    op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_events_session_id'), 'user_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_session_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_category'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_created_at'), table_name='user_events')
    op.drop_index('idx_user_event_user_created', table_name='user_events')
    op.drop_index('idx_user_event_type_created', table_name='user_events')
    op.drop_index('idx_user_event_session_created', table_name='user_events')
    op.drop_index('idx_user_event_device_created', table_name='user_events')
    op.drop_index('idx_user_event_category_type', table_name='user_events')
    op.drop_index('idx_user_event_category_created', table_name='user_events')
    op.drop_table('user_events')
    # ### end Alembic commands ###
