"""align database with models

Revision ID: 35dcf2737325
Revises: cdcb89268b96
Create Date: 2026-01-03 09:24:10.727809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35dcf2737325'
down_revision: Union[str, None] = 'cdcb89268b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_poi_debug_data_map_id'), 'poi_debug_data', ['map_id'], unique=False)
    op.create_index(op.f('ix_poi_debug_data_map_poi_id'), 'poi_debug_data', ['map_poi_id'], unique=False)
    op.alter_column('pois', 'quality_issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pois', 'missing_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_pois_is_low_quality'), table_name='pois')
    op.create_index(op.f('ix_pois_is_low_quality'), 'pois', ['is_low_quality'], unique=False)
    op.drop_index(op.f('idx_problem_reports_created_at'), table_name='problem_reports')
    op.drop_index(op.f('idx_problem_reports_status'), table_name='problem_reports')
    op.create_index('idx_reports_map', 'problem_reports', ['map_id'], unique=False)
    op.create_index('idx_reports_status_created', 'problem_reports', ['status', 'created_at'], unique=False)
    op.create_index('idx_reports_user', 'problem_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_problem_reports_status'), 'problem_reports', ['status'], unique=False)
    op.drop_constraint(op.f('problem_types_name_key'), 'problem_types', type_='unique')
    op.create_index(op.f('ix_problem_types_is_active'), 'problem_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_problem_types_name'), 'problem_types', ['name'], unique=True)
    op.drop_index(op.f('idx_report_attachments_report_id'), table_name='report_attachments')
    op.create_index(op.f('ix_report_attachments_report_id'), 'report_attachments', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_attachments_report_id'), table_name='report_attachments')
    op.create_index(op.f('idx_report_attachments_report_id'), 'report_attachments', ['report_id'], unique=False)
    op.drop_index(op.f('ix_problem_types_name'), table_name='problem_types')
    op.drop_index(op.f('ix_problem_types_is_active'), table_name='problem_types')
    op.create_unique_constraint(op.f('problem_types_name_key'), 'problem_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_problem_reports_status'), table_name='problem_reports')
    op.drop_index('idx_reports_user', table_name='problem_reports')
    op.drop_index('idx_reports_status_created', table_name='problem_reports')
    op.drop_index('idx_reports_map', table_name='problem_reports')
    op.create_index(op.f('idx_problem_reports_status'), 'problem_reports', ['status'], unique=False)
    op.create_index(op.f('idx_problem_reports_created_at'), 'problem_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_pois_is_low_quality'), table_name='pois')
    op.create_index(op.f('idx_pois_is_low_quality'), 'pois', ['is_low_quality'], unique=False)
    op.alter_column('pois', 'missing_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pois', 'quality_issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_poi_debug_data_map_poi_id'), table_name='poi_debug_data')
    op.drop_index(op.f('ix_poi_debug_data_map_id'), table_name='poi_debug_data')
    # ### end Alembic commands ###
