"""add_is_disabled_to_poi

Revision ID: 6438e08a65df
Revises: 2a7fc4962dc7
Create Date: 2026-01-09 01:05:44.521905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6438e08a65df'
down_revision: Union[str, None] = '2a7fc4962dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default to handle existing rows
    op.add_column('pois', sa.Column('is_disabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_pois_is_disabled'), 'pois', ['is_disabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pois_is_disabled'), table_name='pois')
    op.drop_column('pois', 'is_disabled')
    # ### end Alembic commands ###
