"""rename_user_id_to_user_email_in_application_logs

Revision ID: 1d897032655c
Revises: 4bbb723f56c8
Create Date: 2026-01-03 18:10:17.032924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d897032655c'
down_revision: Union[str, None] = '4bbb723f56c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('user_email', sa.String(length=320), nullable=True))
    op.drop_index(op.f('idx_app_log_user_timestamp'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_user_id'), table_name='application_logs')
    op.create_index('idx_app_log_user_email_timestamp', 'application_logs', ['user_email', 'timestamp'], unique=False)
    op.create_index(op.f('ix_application_logs_user_email'), 'application_logs', ['user_email'], unique=False)
    op.drop_column('application_logs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_application_logs_user_email'), table_name='application_logs')
    op.drop_index('idx_app_log_user_email_timestamp', table_name='application_logs')
    op.create_index(op.f('ix_application_logs_user_id'), 'application_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_app_log_user_timestamp'), 'application_logs', ['user_id', 'timestamp'], unique=False)
    op.drop_column('application_logs', 'user_email')
    # ### end Alembic commands ###
