"""add_route_segments_tables

Revision ID: 2a7fc4962dc7
Revises: 0a47b69ae583
Create Date: 2026-01-04 20:58:56.645057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a7fc4962dc7'
down_revision: Union[str, None] = '0a47b69ae583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, delete existing map_pois since they'll be regenerated with the new architecture
    # Existing maps will be recalculated from origin/destination
    op.execute("DELETE FROM map_pois")

    op.create_table('route_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_hash', sa.String(length=32), nullable=False),
    sa.Column('start_lat', sa.Numeric(), nullable=False),
    sa.Column('start_lon', sa.Numeric(), nullable=False),
    sa.Column('end_lat', sa.Numeric(), nullable=False),
    sa.Column('end_lon', sa.Numeric(), nullable=False),
    sa.Column('road_name', sa.String(length=255), nullable=True),
    sa.Column('length_km', sa.Numeric(), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('osrm_instruction', sa.Text(), nullable=True),
    sa.Column('osrm_maneuver_type', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('pois_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_segments_road_name', 'route_segments', ['road_name'], unique=False)
    op.create_index('idx_route_segments_start_coords', 'route_segments', ['start_lat', 'start_lon'], unique=False)
    op.create_index(op.f('ix_route_segments_segment_hash'), 'route_segments', ['segment_hash'], unique=True)
    op.create_table('segment_pois',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('search_point_index', sa.Integer(), nullable=False),
    sa.Column('straight_line_distance_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segment_pois_segment_poi', 'segment_pois', ['segment_id', 'poi_id'], unique=True)
    op.create_index(op.f('ix_segment_pois_poi_id'), 'segment_pois', ['poi_id'], unique=False)
    op.create_index(op.f('ix_segment_pois_segment_id'), 'segment_pois', ['segment_id'], unique=False)
    op.create_table('map_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('distance_from_origin_km', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_map_segments_map_order', 'map_segments', ['map_id', 'sequence_order'], unique=False)
    op.create_index('idx_map_segments_map_segment', 'map_segments', ['map_id', 'segment_id'], unique=True)
    op.create_index(op.f('ix_map_segments_map_id'), 'map_segments', ['map_id'], unique=False)
    op.create_index(op.f('ix_map_segments_segment_id'), 'map_segments', ['segment_id'], unique=False)
    op.add_column('map_pois', sa.Column('segment_poi_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_map_pois_segment_poi_id'), 'map_pois', ['segment_poi_id'], unique=False)
    op.create_foreign_key('fk_map_pois_segment_poi_id', 'map_pois', 'segment_pois', ['segment_poi_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_map_pois_segment_poi_id', 'map_pois', type_='foreignkey')
    op.drop_index(op.f('ix_map_pois_segment_poi_id'), table_name='map_pois')
    op.drop_column('map_pois', 'segment_poi_id')
    op.drop_index(op.f('ix_map_segments_segment_id'), table_name='map_segments')
    op.drop_index(op.f('ix_map_segments_map_id'), table_name='map_segments')
    op.drop_index('idx_map_segments_map_segment', table_name='map_segments')
    op.drop_index('idx_map_segments_map_order', table_name='map_segments')
    op.drop_table('map_segments')
    op.drop_index(op.f('ix_segment_pois_segment_id'), table_name='segment_pois')
    op.drop_index(op.f('ix_segment_pois_poi_id'), table_name='segment_pois')
    op.drop_index('idx_segment_pois_segment_poi', table_name='segment_pois')
    op.drop_table('segment_pois')
    op.drop_index(op.f('ix_route_segments_segment_hash'), table_name='route_segments')
    op.drop_index('idx_route_segments_start_coords', table_name='route_segments')
    op.drop_index('idx_route_segments_road_name', table_name='route_segments')
    op.drop_table('route_segments')
    # ### end Alembic commands ###
