"""add current_phase to async_operations

Revision ID: 7b3cb8d0b056
Revises: 773295308645
Create Date: 2026-01-11 17:11:10.423613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3cb8d0b056'
down_revision: Union[str, None] = '773295308645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('async_operations', sa.Column('current_phase', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('problem_reports_map_id_fkey'), 'problem_reports', type_='foreignkey')
    op.create_foreign_key(None, 'problem_reports', 'maps', ['map_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem_reports', type_='foreignkey')
    op.create_foreign_key(op.f('problem_reports_map_id_fkey'), 'problem_reports', 'maps', ['map_id'], ['id'], ondelete='SET NULL')
    op.drop_column('async_operations', 'current_phase')
    # ### end Alembic commands ###
