"""add frontend_error_logs table and session_id to api_call_logs

Revision ID: 8873067d696c
Revises: 35dcf2737325
Create Date: 2026-01-03 15:24:39.648335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8873067d696c'
down_revision: Union[str, None] = '35dcf2737325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frontend_error_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('component_stack', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('extra_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_frontend_error_session_created', 'frontend_error_logs', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_frontend_error_type_created', 'frontend_error_logs', ['error_type', 'created_at'], unique=False)
    op.create_index('idx_frontend_error_user_created', 'frontend_error_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_frontend_error_logs_created_at'), 'frontend_error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_frontend_error_logs_error_type'), 'frontend_error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_frontend_error_logs_session_id'), 'frontend_error_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_frontend_error_logs_user_id'), 'frontend_error_logs', ['user_id'], unique=False)
    op.add_column('api_call_logs', sa.Column('session_id', sa.String(length=36), nullable=True))
    op.create_index('idx_api_call_session_created', 'api_call_logs', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_call_logs_session_id'), 'api_call_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_call_logs_session_id'), table_name='api_call_logs')
    op.drop_index('idx_api_call_session_created', table_name='api_call_logs')
    op.drop_column('api_call_logs', 'session_id')
    op.drop_index(op.f('ix_frontend_error_logs_user_id'), table_name='frontend_error_logs')
    op.drop_index(op.f('ix_frontend_error_logs_session_id'), table_name='frontend_error_logs')
    op.drop_index(op.f('ix_frontend_error_logs_error_type'), table_name='frontend_error_logs')
    op.drop_index(op.f('ix_frontend_error_logs_created_at'), table_name='frontend_error_logs')
    op.drop_index('idx_frontend_error_user_created', table_name='frontend_error_logs')
    op.drop_index('idx_frontend_error_type_created', table_name='frontend_error_logs')
    op.drop_index('idx_frontend_error_session_created', table_name='frontend_error_logs')
    op.drop_table('frontend_error_logs')
    # ### end Alembic commands ###
