# Configuração de Logging para Debug
# Máximo de detalhes, tudo visível

version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: "%(asctime)s - [%(levelname)s] - %(name)s - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  api:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  api.providers:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: DEBUG
  handlers: [console, file]
